import { Record } from "./types.js";

export const records: Record[] = [
  {
    id: 1,
    name: "Bridges to Babylon",
    artist: "The Rolling Stones",
    coverUrl: "images/covers/rolling-stones-briges-babylon.webp",
    type: "VINYL",
    price: 21.99,
    isRecordOfTheMonth: false,
  },
  {
    id: 2,
    name: "Sueño su boca",
    artist: "Raúl",
    coverUrl: "images/covers/raul-sueno-su-boca.webp",
    type: "VINYL",
    price: 99.99,
    originalPrice: 119.99,
    isRecordOfTheMonth: false,
  },
  {
    id: 3,
    name: "Temple of the Dog",
    artist: "Temple of the Dog",
    coverUrl: "images/covers/temple-of-the-dog-temple-of-the-dog.webp",
    type: "DIGITAL",
    price: 23.99,
    isRecordOfTheMonth: false,
  },
  {
    id: 4,
    name: "Whenever you need somebody",
    artist: "Rick Astley",
    coverUrl: "images/covers/rick-astley-whenever-you-need-somebody.webp",
    type: "DIGITAL",
    price: 269.99,
    originalPrice: 359.99,
    isRecordOfTheMonth: false,
  },
  {
    id: 5,
    name: "Marifé de Triana",
    artist: "Marifé de Triana",
    coverUrl: "images/covers/marife-de-triana-marife-de-triana.webp",
    type: "VINYL",
    price: 219.99,
    isRecordOfTheMonth: false,
  },
  {
    id: 6,
    name: "Show me love",
    artist: "Robin S",
    coverUrl: "images/covers/robin-s-show-me-love.webp",
    type: "DIGITAL",
    price: 19.99,
    isRecordOfTheMonth: false,
  },
  {
    id: 7,
    name: "Homework",
    artist: "Daft Punk",
    coverUrl: "images/covers/daft-punk-homework.webp",
    type: "VINYL",
    price: 24.59,
    isRecordOfTheMonth: false,
  },
  {
    id: 8,
    name: "El Chiringuito",
    artist: "Georgie Dann",
    coverUrl: "images/covers/georde-dann-el-chiringuito.webp",
    type: "VINYL",
    price: 1.99,
    isRecordOfTheMonth: true,
  },
  {
    id: 9,
    name: "Deep Purple in Rock",
    artist: "Deep Purple",
    coverUrl: "images/covers/deep-purple-deep-purple-in-rock.webp",
    type: "VINYL",
    price: 27.49,
    isRecordOfTheMonth: false,
  },
  {
    id: 10,
    name: "Led Zeppelin IV",
    artist: "Led Zeppelin IV",
    coverUrl: "images/covers/led-zepelin-iv-led-zepelin.webp",
    type: "VINYL",
    price: 34.99,
    isRecordOfTheMonth: false,
  },
  {
    id: 11,
    name: "Raro",
    artist: "El Cuarteto de Nos",
    coverUrl: "images/covers/raro-el-cuarteto-de-nos.webp",
    type: "DIGITAL",
    price: 19.99,
    originalPrice: 39.99,
    isRecordOfTheMonth: false,
  },
  {
    id: 12,
    name: "De paso / Libertad",
    artist: "Luis Eduardo Aute",
    coverUrl: "images/covers/aute-de-paso-libertad.webp",
    type: "DIGITAL",
    price: 23.99,
    isRecordOfTheMonth: false,
  },
];
