import { Record } from "./types.js";

export const records: Record[] = [
  {
    id: 1,
    name: "The Human Fear",
    artist: "Franz Ferdinand",
    coverUrl: "public/images/cover.webp",
    type: "DIGITAL",
    price: 12,
    isRecordOfTheMonth: true,
  },
  {
    id: 2,
    name: "The Human Fear",
    artist: "Franz Ferdinand",
    coverUrl: "public/images/cover.webp",
    type: "VINYL",
    price: 12,
    isRecordOfTheMonth: true,
  },
  {
    id: 3,
    name: "The Human Fear",
    artist: "Franz Ferdinand",
    coverUrl: "public/images/cover.webp",
    type: "VINYL",
    price: 12,
    isRecordOfTheMonth: true,
  },
  {
    id: 4,
    name: "The Human Fear",
    artist: "Franz Ferdinand",
    coverUrl: "public/images/cover.webp",
    type: "DIGITAL",
    price: 12,
    isRecordOfTheMonth: true,
  },
  {
    id: 5,
    name: "The Human Fear",
    artist: "Franz Ferdinand",
    coverUrl: "public/images/cover.webp",
    type: "VINYL",
    price: 12,
    isRecordOfTheMonth: true,
  },
  {
    id: 6,
    name: "The Human Fear",
    artist: "Franz Ferdinand",
    coverUrl: "public/images/cover.webp",
    type: "VINYL",
    price: 12,
    isRecordOfTheMonth: true,
  },
  {
    id: 7,
    name: "The Human Fear",
    artist: "Franz Ferdinand",
    coverUrl: "public/images/cover.webp",
    type: "VINYL",
    price: 12,
    isRecordOfTheMonth: true,
  },
  {
    id: 8,
    name: "The Human Fear",
    artist: "Franz Ferdinand",
    coverUrl: "public/images/cover.webp",
    type: "DIGITAL",
    price: 12,
    isRecordOfTheMonth: true,
  },
];
